version: "3.9"

services:
  web:
    image: fatimazaidan26/genai-assistant:latest
    container_name: genai_web
    ports:
      - "7870:7860"
    environment:
      - DATABASE_URL=postgresql+psycopg2://rag_role:mypassword@db:5432/rag_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    container_name: genai_db
    environment:
      POSTGRES_USER: rag_role
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_new:
